### ISSUE TITLE
Support #[serde(rename)] for enum variants

### ISSUE THREAD

**Issue by kimpers** [Aleph-Alpha/ts-rs#119] opened 2022-09-20 09:05 UTC
Thanks for an awesome library. However, the lack of `#[serde(rename)]` support is blocking me from using it in production.

**Example**
```rust
#[derive(Serialize, Deserialize, TS)]
#[serde(tag = "kind")]
#[ts(export)]
pub enum Shapes {
    #[serde(rename = "SQUARE_THING")]
    SquareThing {
        name: String,
        // ...
    },
}
```

**Warning**
```
warning: failed to parse serde attribute
  |
  | #[serde(rename = "SQUARE_THING")]
  |
  = note: ts-rs failed to parse this attribute. It will be ignored.
```
**Actual result**
The types have en incorrect TS enum
```typescript
export type SquareThing =
  | {
      kind: "squareThing";
      name: string
    };
```

**Expected result**
```typescript
export type SquareTing =
  | {
      kind: "SQUARE_THING";
      name: string
    };
```

**Comment by phoneticsushi** [comment] 2022-10-09 21:09
Independently encountered a similar issue.  This seems highly related to (if not a duplicate of) #72 - might be worth subscribing to that one.

**Comment by phoneticsushi** [comment] 2022-10-10 06:31
Hi again - I was trying to resolve the issue with `#[serde(rename_all)]`, which doesn't work, but it looks like `#[serde(rename)]` works fine:

```rust
#![allow(dead_code)]

use serde::{Serialize, Deserialize};
use ts_rs::TS;

#[derive(Serialize, Deserialize, TS)]
#[serde(tag = "kind")]
#[ts(export)]
pub enum Shapes {
    #[serde(rename = "SQUARE_THING")]
    SquareThing {
        name: String,
        // ...
    },
}

#[test]
fn test_enum_variant_with_tag() {
    assert_eq!(
        Shapes::inline(),
        "{ kind: \"SQUARE_THING\", name: string, }"
    );
}
```
Have you tried this again recently?  The above works on commit `b79cb2a274df40da19686fee65f1142f5da4e272`

**Comment by NyxCode** [comment] 2022-10-20 11:05
A new release is long overdue :D 
But yes, it works on master.

**Closed by NyxCode** 2022-10-20 11:05 UTC
