### ISSUE TITLE
Exporting enum discriminants

### ISSUE THREAD

**Issue by alexwaeseperlman** [Aleph-Alpha/ts-rs#153] opened 2023-06-21 04:21 UTC
I would like to export a struct that looks like this
```rs
#[derive(Serialize, Deserialize, Debug, Clone, TS)]
#[ts(export)]
pub enum BuildStatus {
    Unqueued = -1,
    Queued = 0,
    Building = 1,
    BuildFailed = 2,
    TestGameFailed = 3,
}
```
into a format that looks like this:
```ts
export enum BuildStatus {
    Unqueued = -1,
    Queued = 0,
    Building = 1,
    BuildFailed = 2,
    TestGameFailed = 3,
}
```
This is what was generated:
```ts
export type BuildStatus = "Unqueued" | "Queued" | "BuildSucceeded" | "TestGameSucceeded" | "BuildFailed" | "TestGameFailed";
```
Is there a way to get an enum in typescript with the same discriminants as in rust?

**Comment by flukejones** [comment] 2023-06-27 06:12
I'm in need of this also

**Comment by raine** [comment] 2023-08-12 08:59
I thought I would need this but it turned out that the enum values are serialized to their string representation when sent as JSON response from axum. So I can use the literal string representation in the TypeScript code, Rust enum in rust code, and in the database the enum is stored as an integer.

```ts
#[repr(i32)]
#[derive(Hash, Eq, Debug, PartialEq, sqlx::Type, TS, Serialize, Deserialize, Clone, Copy)]
#[serde(rename_all = "snake_case")]
#[ts(export)]
pub enum MyEnum {
    Foo = 1,
    Bar = 2,
}
```

**Comment by escritorio-gustavo** [comment] 2024-01-26 12:09
Duplicate of #23

**Closed** 2024-01-26 12:09 UTC
