### ISSUE TITLE
#[derive(TS)] requires all generics in fields to implement TS

### ISSUE THREAD

**Issue by Heliozoa** [Aleph-Alpha/ts-rs#32] opened 2021-09-29 11:09 UTC
Hi,
Currently deriving for types that have fields like `DateTime<Utc>` which have TS impls that do not require the generic parameter to implement TS is broken because the derive macro generates code that requires Utc to implement TS. For example

```rs
use ts_rs::TS;

struct Generic<T> {
    t: T
}

impl<T: 'static> TS for Generic<T> {
    fn name() -> String {
        "string".to_string()
    }

    fn dependencies() -> Vec<(std::any::TypeId, String)> {
        vec![]
    }

    fn transparent() -> bool {
        false
    }
}

struct Struct;

#[derive(TS)]
struct ContainsGenerics {
    g: Generic<Struct>,
}
```
gives 
```console
error[E0277]: the trait bound `Struct: TS` is not satisfied
   --> src/main.rs:23:10
    |
23  | #[derive(TS)]
    |          ^^ the trait `TS` is not implemented for `Struct`
    |
note: required by `name`
```
As far as I can tell the problem is the special handling done in `types::generics::format_type`. The derive macro should rely on the TS impl of DateTime<Utc> without processing the generic parameter.

**Comment by NyxCode** [comment] 2021-09-29 11:20
You're right! I'll look into this. Maybe @arendjr can also chime in?

**Comment by NyxCode** [comment] 2021-09-29 11:20
Minimal example to reproduce:
```rust
#[derive(TS)]
struct ContainsDate {
    date: DateTime<Utc>
}
```

**Comment by arendjr** [comment] 2021-09-29 12:01
I see, this seems an unfortunate interaction between the `TS` implementation for `DateTime<T>` with the updated generics support. To be able to support generics generally, we need to traverse recursively through type arguments, but indeed this specific situation longs for an exception. To indicate we wish to apply an exception for a type, the type would need to indicate this somehow. To complicate matters, this should be detectable *before* the codegen takes place, so a solution similar to `::transparent()` would not suffice, I'm afraid.

The easiest way out seems to be to simply implement `TS` for `Utc`, but that can become cumbersome as users keep asking for more timezones and other types to be similarly implemented.

For @Heliozoa's case, I would suggest doing this instead:

```rs
#[derive(TS)]
struct ContainsGenerics {
    #[ts(type = "string")]
    g: Generic<Struct>,
}
```

This way the issue is avoided altogether (in fact, that was what I did myself for `DateTime<Utc>` before `DateTime<T>` received an out-of-the-box `TS impl`).

**Comment by Heliozoa** [comment] 2021-09-29 12:42
> The easiest way out seems to be to simply implement `TS` for `Utc`, but that can become cumbersome as users keep asking for more timezones and other types to be similarly implemented.

I tried a couple of simple fixes including that one, but it resulted in `string<something>`. For now I've added
```rs
    if let Type::Path(path) = ty {
        if path.path.segments.first().unwrap().ident.to_string().contains("DateTime") {
            return quote!(<#ty as ts_rs::TS>::name());
        }
    }
```
in my fork before last part of `format_type`.

I haven't looked at the issue too deeply yet, but I imagine it should be possible to call the same method for all types without looking at whether the field is generic or not. Like how the `inline` implementation for `Vec<T>` returns `format!("Array<{}>", T::inline(indent))`, you would just delegate handling (or not handling) the generics to the method.

**Comment by NyxCode** [comment] 2021-09-29 13:10
The current design is based on the idea that `A<B>: TS` implies `B: TS`. This seems sensible.
We *could* create a dummy implementation for the chrono timezones, or tell users to use `#[ts(type = "string")]`. I'll have to think about that.
What I wouldn't want to do is to check for special cases within the macros - We don't have typing information there, and just going by name is too hacky imho.

**Comment by NyxCode** [comment] 2021-09-29 14:09
Hm, yeah, I *think* that could work? 😄 I can't fully think this through, I'll have to do some experimentation.

**Comment by NyxCode** [comment] 2021-11-11 16:41
Fir the upcoming release, I just implemented `TS` for `Utc`, `Local` and `FixedOffset`, so that fixes the issue at hand.  
There were also quite a few issues I discovered & fixed, like having a struct like 
```rust
#[derive(TS)]
struct MyStruct {
    field: (Vec<String>, Vec<String>)
}
```
This is now fixed by handling tuple (and array) fields explicitly. In this particular case, I converted the field to its own struct `struct A(Vec<String>, Vec<String>)` and used the existing machinery for generating bindings for that.
---
So I'd say I'll close this as *wontfix*. Feel free to comment though if there is anything you'd like to say.

**Closed by NyxCode** 2021-11-11 16:41 UTC

**Comment by NyxCode** [comment] 2021-11-11 16:44
@arendjr 
> The easiest way out seems to be to simply implement TS for Utc, but that can become cumbersome as users keep asking for more timezones and other types to be similarly implemented.

There are only 3 timezones in chrono, so i came to the conclusion that that's the best thing to do. 
In general, I'd say that requiring that generic arguments implement TS as well is not *super* unreasonable, though it requires some understanding of the implementation to get *why*.

**Comment by dedupely** [comment] 2024-03-26 23:51
I'm using Diesel and it uses DateTime<Utc> a lot in its models. I'm very new to Rust and I'm not 100% sure how this should work:

```
#[derive(TS)]
struct ContainsGenerics {
    #[ts(type = "string")]
    g: Generic<Struct>,
}
```
I'm not sure what this should do. This means any generic type? Confused.


So basically DateTime<Utc> is perfect for the object model because otherwise I'll need to deal with some other type, which is not ideal.

Why can't ts-rs try for all timezones? I mean I get that it's ugly, but I imagine lots of people are going to need at least UTC and it sucks to have to convert strings to Date objects in Typescript, too much extra code for nothing.

Not trying to be an a-hole here just saying I think it's a pretty common use case and dates are inconvenient to parse depending on where they land in the frontend. Also in Rust it's going to be a pain to have to convert the type everytime we want to use them in the code. Why not kill the problem from the root, even if it's a little ugly?

**Comment by NyxCode** [comment] 2024-03-27 07:35
I am confused by your last message @dedupely. Please explain clearly what issue you're facing.

This issue is very old, and the problems described here have been supported for quite a while.
